### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by nimaen** [Elium/mighty-js#1]
Bootstrap the project, which includes :
- TypeScript.
- Bower.
- Grunt.
- Karma / TypeScript unit testing tools ?

**Comment by firehist** [comment]
Can we add here *CI* (drone, Travis) ?
Cross-browser testing (saucelabs: https://saucelabs.com/opensauce) ?
NPM package.json to be able to use this lib both on client & server side?

**Comment by nimaen** [comment]
@firehist Indeed, feel free to bootstrap this.
I've already done some stuff on `feature/utils`, might a good start point.

**Comment by nimaen** [comment]
closed with #11
