### ISSUE TITLE
Should we remove RxJS ?

### ISSUE THREAD

**Issue by nimaen** [Elium/mighty-js#23]
In fact, there is no need to use RxJS here since we never receive a sequence of results.
Each method should be atomic : one call, on result, bang bang :bangbang:

**Comment by firehist** [comment]
Dunno why you said that RxJS is not useful with atomic methods.
RxJS provides an immutable state store, which cna be use in deferent ways, no?

**Comment by nimaen** [comment]
Yes indeed, but we're not using RxJS that much here : just a call then some maps on it.
That could be done with plain Futures / promises.
I was wondering if we should keep it or not in fact, it should not be a to do :)

**Comment by firehist** [comment]
I think that we can keep it, 'cause since we'll include a sidebar, a login or so on.
We'll be able to use state and reducer.

**Comment by nimaen** [comment]
Got it ;)
